### ISSUE TITLE
Module import error with v0.1.0

### ISSUE THREAD

**Issue by sarenji** [mitchlloyd/ember-screen#1]
Hey there! New-ish to Ember, so I hope I'm clear enough.

I'm using Ember `v2.3.0`. I installed `ember-screen` today via `ember install ember-screen`. I built my Ember app, which succeeded. Then I navigated to the page in the browser, but got this error in the console:

```
Uncaught Error: Could not find module `css-mediaquery` imported from `ember-screen/window`
```

I noticed that `v0.1.0` introduces a dependency on `css-mediaquery`, but I'm too new to Ember and addons to figure out why it's erroring, since you seem to shim and import the library. If it's helpful, the error pops up when I use `screen: Ember.inject.service()`, but disappears when I comment that out. Any ideas?

Let me know if I can include anything else or be more helpful. Thanks for your time!

**Comment by MartinMalinda** [comment]
I'm seeing this error on Ember 2.12 when using `ember-screen` inside and an engine app

**Comment by mitchlloyd** [comment]
@MartinMalinda Thanks for reporting this. I have not used Ember Engines so I'm not sure how the npm module importing works differently in this case. Is it possible to create a minimal Github repo to reproduce?

Also are you seeing any warning messages like those mentioned here: https://github.com/ember-engines/ember-engines/pull/317
