### ISSUE TITLE
Release for Ember 4.0

### ISSUE THREAD

**Issue by XuluWarrior** [mitchlloyd/ember-screen#14]
ember-screen 1.0.0 is broken in Ember 4.0 due to the removal of all previously deprecated APIs.

However, changes in master (#10) have fixed the broken behaviour.

Any chance of a new release for those that have already moved to Ember 4.0?

**Comment by gilest** [comment]
@mitchlloyd any chance you could cut a release from latest master?

**Comment by mitchlloyd** [comment]
I just released `ember-screen@2.0.0-beta.0`. @XuluWarrior and @gilest could you let me know if this version is working for you? If so I'll follow up with a 2.0 release.

**Comment by gilest** [comment]
Tysm @mitchlloyd . I'll test it and get back to you.

Edit: Actually we've been running 03d340718 in prod for six months on a high traffic fast-booted website with no issues. Note that this site is still running Ember 3.28, though.

**Comment by XuluWarrior** [comment]
We've also been running against 03d34071806ba077b1ba5f32a3245d46d057fbac since I raised the original issue.  We've had no problems with it.

**Comment by pabloascarza** [comment]
@mitchlloyd Can you release 2.0 pls. Worked on our app.

**Comment by pabloascarza** [comment]
> @mitchlloyd Can you release 2.0 pls. Worked on our app.

@mitchlloyd any updates on this??

**Comment by mitchlloyd** [comment]
Thanks for the follow up, @pabloascarza. Just realeased `ember-screen@2.0.0-beta.0` as `ember-screen@2.0.0`.

**Comment by pabloascarza** [comment]
> Thanks for the follow up, @pabloascarza. Just realeased `ember-screen@2.0.0-beta.0` as `ember-screen@2.0.0`.

no thanks to you man
