### ISSUE TITLE
Ensure default value set during tests

### ISSUE THREAD

**Issue by samselikoff** [mitchlloyd/ember-screen#4]
We just got bit because tests were passing on an external monitor and failing on laptop, took us a while to figure out why.

I think the addon should warn/throw if you haven't set a default value for your tests.

**Comment by mitchlloyd** [comment]
I'm imagining a scenario where someone installs this addon to handle a small use case in their app, and suddenly all of their tests are failing or the console is filled with warnings. That would probably make me uninstall that addon. As it is now, the situation is no worse than running tests without the addon installed. 

Would it be better to document and encourage people to add defaults to their `moduleForAcceptance` function? Maybe there could be some configuration in `config/environments.js` that turns on `requireStubMediaFeatures`.

**Comment by samselikoff** [comment]
We could also do an in-memory default of `desktop` and print a warning/message when running tests that "No default is set, please specify an explicit size in `config/environment`"

**Comment by samselikoff** [comment]
Also if you add this addon, the only tests that could start failing would be ones that somehow touch this addon's service right? In that case a failure could be ok
